### ISSUE TITLE
Use of Unphased VCF Files

### ISSUE THREAD

**Issue by Mahmoudbassuoni** [coriell-research/ursaPGx#2]
Hi, 
I am interested in using your package, but I have a question regarding the technicalities of the tool. I have a list of UNPHASED vcf files for genes that are produced from a WGS for human data, and I need to apply it as input here to get the star alleles. The question is, would it be suitable as input? And if not, what is the best suitable method to make it phased?

Thanks,

**Comment by Mahmoudbassuoni** [comment]
Hi @jcalendo,
I would appreciate your answer. 

Thanks,

**Comment by jcalendo** [comment]
At the moment, ursaPGx does not accept unphased VCF files as input. This functionality might be added in the future when I get more time but was not initially one of our priorities.

The best method phasing method is highly dependent on your data and the samples that you have collected (e.g. parent-offspring trios vs single samples, etc.). That being said, the NYGC used SHAPEIT2 for statistical phasing of the 1kGP samples which we then analyzed in the ursaPGx paper for star allele calling. I believe a newer version of SHAPEIT, [SHAPEIT5](https://odelaneau.github.io/shapeit5/), was recently released and might be worth running on your data to produce phased VCFs for use with ursaPGx.

I hope this helps.
