### ISSUE TITLE
Input data type

### ISSUE THREAD

**Issue by EmMaKaa** [coriell-research/ursaPGx#3]
Hi,

in your paper, you used 30x WGS data for the analyses. I'm interested in whether this tool would be suitable for imputed GWAS data?

Thank you!

**Comment by jcalendo** [comment]
We recommend against using imputed data as input for ursaPGx. ursaPGx assumes that all variants (rare and common) are being directly measured. All errors in imputation will directly result in errors in the ursaPGx output annotations.
